id: PCF76542B
initial_creation_type: ocr
source_metadata:
  volumes:
    9a7109ee25254e8e853b0ada32b3411d:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བྱང་ཆུབ་ཀྱི་སེམས་བསྒོམ་པ།
      total_pages: 1902
      volume_number: 64
